M48
; DRILL file {KiCad 6.0.4+dfsg-1+b1} date Fri 06 May 2022 01:05:33 +08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-06T01:05:33+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.65Y-2.9
X3.65Y-4.6
X6.35Y-2.9
X6.35Y-4.6
T0
M30
