M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Sat 10 Sep 2022 20:58:08 +08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-10T20:58:08+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.7726Y1.1388
X2.7726Y0.9112
T2
X0.175Y1.875
X0.175Y0.175
X2.875Y1.875
X2.875Y0.175
T0
M30
