M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Sat 10 Sep 2022 15:38:15 +08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-10T15:38:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.15Y1.85
X0.15Y0.15
X2.85Y1.85
X2.85Y0.15
T0
M30
