M48
; DRILL file {KiCad 7.0.5+dfsg-2} date Thu 13 Jul 2023 13:02:38 +08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-13T13:02:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5+dfsg-2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.715Y48.895
X5.715Y5.715
X74.295Y48.895
X74.295Y5.715
T0
M30
