M48
; DRILL file {KiCad 7.0.6+dfsg-1} date Fri 25 Aug 2023 11:52:43 +08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-25T11:52:43+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X149.86Y-99.06
X149.86Y-142.24
X218.44Y-99.06
X218.44Y-142.24
T0
M30
