M48
; DRILL file {KiCad 7.0.5+dfsg-2} date Thu 13 Jul 2023 12:51:56 +08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-13T12:51:56+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5+dfsg-2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X92.015Y44.165
X92.015Y38.385
T2
X26.035Y62.865
X26.035Y19.685
X94.615Y62.865
X94.615Y19.685
T0
M30
