M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Wed 14 Sep 2022 16:01:18 +08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-14T16:01:18+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X85.665Y37.815
X85.665Y32.035
T2
X19.685Y56.515
X19.685Y13.335
X88.265Y56.515
X88.265Y13.335
T0
M30
