M48
; DRILL file {KiCad 6.0.4+dfsg-1+b1} date Thu 05 May 2022 09:05:36 +08
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-05T09:05:36+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.425Y-2.975
X4.425Y-4.675
X7.125Y-2.975
X7.125Y-4.675
T0
M30
