M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2025-06-14T15:38:49+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-14T15:38:49+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X124.46Y-73.66
X124.46Y-116.84
X193.04Y-73.66
X193.04Y-116.84
M30
